on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests beautifulsoup4 selenium
      - run: python app.py > data
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: data
          commit_message: update

